### ISSUE TITLE
New way of checking for uncommitted Drupal config changes brought by database updates

### ISSUE THREAD

**Issue by Leksat** [amazeeio-solutions/silverback-mono#1001]
We need it in
- `silverback-mono`
- `amazee/recipes`

I will link this issue from a private repo PR where it was already implemented.

**Comment by Leksat** [comment]
We also need the following (missing in the linked PR):

```if: startsWith(github.head_ref, 'test-all/') == true```

**Comment by pmelab** [comment]
Duplicates #1019
