### ISSUE TITLE
EX: Show live/preview version on node page in Drupal

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#1062]
On Drupal node pages, the iframe with the current live or preview version of the page should be displayed.

- Make it possible to enable/disable loading of latest version (e.g. GET-parameter)
- Replicate "latest revision" tab when content moderation is in use.

**Comment by colorfield** [comment]
This will be integrated in `silverback_external_preview` package.

@pmelab, a summary of the discussed UX topics
- On the node 'View' tab, we could have a selector to view the current live or preview version (to append the `preview` GET parameter)
- As the 'Latest revision' tab will show only non default revision, we could skip this selector and always use preview
- When the preview buttons are opened, they are hiding the Save button on Claro, so until we have auto-save it requires to collapse the buttons to hit save. Current resolution could be to delegate this to the Drupal behavior that redirects to 'View' / 'Latest revision' tabs on save.

**Comment by colorfield** [comment]
@pmelab view tab integration is done here https://github.com/AmazeeLabs/silverback-mono/commit/769444d5996071135b6c1d258b673e7ead38b927, i will wait for https://github.com/AmazeeLabs/silverback-mono/pull/1085 to be merged to add the last revision tab support
