### ISSUE TITLE
Ouput Webp variants

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#1111]
All images should also provide a webp-variant: https://www.drupal.org/project/webp

**Comment by stewest** [comment]
Hi @pmelab @Leksat , I can maybe help with this one, but how does one start?

**Comment by Leksat** [comment]
@stewest this is an issue from [Image Handling milestone](https://github.com/AmazeeLabs/silverback-mono/milestone/2). I believe we should go from top to bottom there. As currently we have no common image related code in silverback-mono.

**Comment by stewest** [comment]
Thanks @Leksat - looks like that first one is pretty complex. Will watch for when the first few are done.
