### ISSUE TITLE
Send notification if build fails

### ISSUE THREAD

**Issue by isara89** [amazeeio-solutions/silverback-mono#1115]
To being informed pro-actively about failing builds, a notification should be sent to a desired service (Slack channel, e-mail,..). 
--
**As a** project maintainer (Dev, PM)
**I want** to be automatically informed if a build fails
**So** I can take necessary actions to get the build running again
--
Includes environment information.

**Comment by pmelab** [comment]
I suppose this is about the publisher package.

**Comment by isara89** [comment]
Yes, related to the publisher package. :-)
