### ISSUE TITLE
Generalize preview url for the toolbar and the iframe

### ISSUE THREAD

**Issue by colorfield** [amazeeio-solutions/silverback-mono#1123]
- Generalize preview url and use the same method for the toolbar and the iframe (entity based path, with `__preview` path prefix). Currently the `__preview` path only applies to unpublished entities and revisions urls.
- Keep BC: make this configurable and use the legacy preview by default (route context based, public Gatsby path, no `__preview` prefix), so we do not alter the behavior of existing sites

Note: entity based path with `__preview` prefix supports path changes and does not require to be published, this is why this change was introduced.

Package: `silverback_external_preview`

**Comment by pmelab** [comment]
Based on the change of scope, we should streamline the implementation of the external preview a little:

- [ ] it has to work for nodes only
- [ ] it should be configured by setting `$settings['external_preview_host'] = '...';` in `settings.php`
- [ ] all preview displays should go to `[external_preview_host]/__preview/[bundle machine name]?nid=1&rid=1&lang=en`
- [ ] live version goes to `[external_preview_host]/[node path]`

ways to accomplish:

- add a submodule that alters the current behavior
- create version 2 and throw away half of the stuff

**Comment by nbaosullivan** [comment]
Hi @pmelab , the changes requested are here now: https://github.com/AmazeeLabs/silverback-mono/pull/1288
