### ISSUE TITLE
Status button improvements

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#1139]
Drupal status button should become more functional and user friendly:

- [x] "Fatal Error!!!" is not very encouraging
- [x] Start build
- [x] Show status page/logs
- [ ] more emojis!

Maybe the status button should be moved to a dedicated npm package with its own lit-element build process, since it's different to anything else.

[Stencil](https://stenciljs.com/) could also be an interesting option.

**Comment by stewest** [comment]
Some questions:

1. should we include a new package [here](https://github.com/AmazeeLabs/silverback-mono/tree/development/packages/npm/@amazeelabs)  

2. Do we want the new <publisher-status> lit-element to take in props and be included in https://github.com/AmazeeLabs/silverback-mono/blob/development/packages/npm/%40amazeelabs/publisher/src/elements/Status.ts#L38 ?

3. I had a look at Stencil. It gave me erratic results initially, but may be a setup issue with pnpm.

Chat soon

**Comment by stewest** [comment]
Stencil seems to still have pnpm issues https://github.com/ionic-team/stencil/issues/3266

**Comment by stewest** [comment]
checking https://www.npmjs.com/package/@storybook/html

**Comment by stewest** [comment]
now having issue https://github.com/storybookjs/storybook/issues/18552

**Comment by stewest** [comment]
Hi @pmelab - as @Leksat is going to be doing some work on larger Publisher package (splitting out the elements) and working on getting them to build on their own with tailwind etc, it may be best for us to wait on this. I just may not be here to complete it.
