### ISSUE TITLE
Empty queue on Publisher clean

### ISSUE THREAD

**Issue by colorfield** [amazeeio-solutions/silverback-mono#1251]
## Motivation

The _Clean_ button triggers a full build. If an error was met, queued jobs can pile up. 
We could empty the queue as a side effect so we make sure that next incremental builds can go on.
Current resolution is to kill the process manually.

The build id might need to be checked as well to make sure that the build info query is still correct.

## Package

`publisher`

**Comment by isara89** [comment]
@Leksat is this covered by #1287? If yes, please close this issue. Thank you!

**Comment by Leksat** [comment]
Publisher 2 has a single job queue. If `Clean` is triggered:
- all current jobs are killed
- queue is emptied
- `clean` and `build` jobs are added to the queue
