### ISSUE TITLE
Listen to other errors than build or gateway

### ISSUE THREAD

**Issue by colorfield** [amazeeio-solutions/silverback-mono#1252]
## Motivation

We are observing build or gateway errors to send a Slack notification #1115 or update the CMS status.
We could upcast other potential errors so they can be observed as well, or make the build fail so observers can be aware of the error.

We've met 2 errors that didn't make the build fully fail:

Example, during an incremental build
```
WebpackError: Cannot find module './component---src-templates-content-second-level-page-tsx.js'
```
Not sure about the cause, but it was not triggered by a code change.

Example, during a full build
```
warning Query IntrospectionQuery returned status 503. Query variables: {}
error "@amazeelabs/gatsby-source-silverback" threw an error while running the createSchemaCustomization lifecycle
```

After some debug it seems that the root cause of this second example was a memory leak because killing the build process led to a Kubernetes error
```
command terminated with exit code 137
```
so this should be infrastructure related (e.g. during planned maintenance).

## Related issue

#1251

## Package

`publisher`

**Comment by isara89** [comment]
@Leksat is this covered by #1287? If yes, please close this issue. Thank you!

**Comment by Leksat** [comment]
With Publisher 2 we have [`outputTimeout`](https://github.com/AmazeeLabs/silverback-mono/blob/470d56f2d75ad5f6ab6bc726cb21f61d2802fdea/packages/npm/%40amazeelabs/publisher/src/core/tools/config.ts#L29-L33) which marks the build as errored if we don't see new output from the build process within a given time interval. I hope it will cover the rest of glitches. For example, when `gatsby build` gets stuck but does not exit.
