### ISSUE TITLE
Re-write publisher logic

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#1287]
Publishers job-management and notification system is built on top of [RxJS](https://rxjs.dev/), which is unfortunately hard to understand and maintain. Currently hard to reproduce race conditions lock the system up. A this point i think it would be better to switch to a easier to understand state model (zustand or xstate) and re-implement queueing and processing there.

Related:
- #1140 
- #1252 
- #1251

**Comment by Leksat** [comment]
@pmelab Do you know if it makes sense to preserve Gatsby's `public` dir in the persistent store? Maybe just `.cache` is enough?
