### ISSUE TITLE
Drupal / Netlify redirects

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#1348]
Integrate redirects that are emitted from Drupal into Netlify hosted websites.

Up until now this was solved using the [`silverback_cdn_redirect`](https://github.com/AmazeeLabs/silverback-mono/tree/development/packages/composer/amazeelabs/silverback_cdn_redirect) module, which works, but is rather complicated around edge cases like 404 pages.

Netliy Edge handlers could provide a easier, faster and more maintainable solution (@pmelab already has a prototype):

1. If a request yields a 404 from netlify, request the same path from drupal
2. if drupal yields a redirect response, just send it back
3. if drupal yields 404, just return netlify's 404 response for a proper 404 page

**Comment by isara89** [comment]
@pmelab can this issue be closed? Related ticket (https://amazeelabs.atlassian.net/browse/SLB-179) was closed too.
