### ISSUE TITLE
FOUC when https://silverback.netlify.app/ docs site renders

### ISSUE THREAD

**Issue by bryangruneberg** [amazeeio-solutions/silverback-mono#181]
*Background*
When https://silverback.netlify.app/ opens, there is a flash of unstyled content on page render.

*To replicate*
Simply browse to https://silverback.netlify.app/

*Expected behavior*
There is no unstyled content flash on page load

**Comment by marcotisi** [comment]
Should be fixed by 75d7849597291da23a449b857752e08de08be6d1, let's see how it behaves once PR is merged and deployed to Netlify
