### ISSUE TITLE
Set up automation identity

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#199]
Currently, all automation uses my accounts (drupal.org, github).

We need to create a common entity that acts as a virtual "person" to be registered with all endpoints. It should have an email address, ssh keys and accounts on github, drupal.org, and whatever other services it has to interact with.

- [ ] find a fun name, email and gravatar for our butler
- [ ] make sure its maintainer of all packages on drupal.org
- [ ] make sure it's part of the tech team
- [ ] make sure it can publish to npm

**Comment by dan2k3k4** [comment]
I see we are using `developers@amazeelabs.com` in the package author, I don't know if that account exists but we could add it as a group alias to all devs.

https://github.com/AmazeeLabs/silverback-mono/blob/3ba11ae02af2f4ff0713ebc24677d317cb812970/packages/npm/%40amazeelabs/ui/package.json#L6

**Comment by marcotisi** [comment]
I would use `developers@amazeelabs.com` as email as @dan2k3k4 suggested 👍

**Comment by Leksat** [comment]
For the record. Recently we tried to setup branch protection rules for `development`. This leaded to this in the Publish build:
```
lerna WARN gitPush remote: error: At least 1 approving review is required by reviewers with write access.        
lerna WARN gitPush To https://github.com/AmazeeLabs/silverback-mono
```

I tried to exclude kitt@amazee.com in the rule, but Github only accepts Github usernames. So I just deleted the branch protection rule for now.

**Comment by dan2k3k4** [comment]
Perhaps try with http://github.com/amazee-labs-kitt (See Lastpass for info)
