### ISSUE TITLE
Auto-configure code quality tooling

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#328]
In #299 some tools were added to simplify continuous code quality feedback. The `@amazeelabs/jest-preset` and `@amazeelabs/jest-preset-react` packages come with all dependencies necessary to run type checks, lint checks, prettier and unit tests efficiently during development and before committing.

The configuration still has to be done manually. Ideally it happens automatically when installing either of the `jest-preset` packages:

```bash
# create a new package
yarn init
# add the jest preset
yarn add @amazeelabs/jest-preset
# start local development
yarn test
# you may write code now!
```

These are the configurations that need to be auto-installed. Almost all of them can live either in dotfiles or directly in package.json.

### ESLint
https://github.com/AmazeeLabs/silverback-mono/blob/d1e016eb43a1549d9d385595b8cbd0321c295cbf/apps/silverback-website/.eslintrc.js#L1-L3

### Prettier
https://github.com/AmazeeLabs/silverback-mono/blob/d1e016eb43a1549d9d385595b8cbd0321c295cbf/apps/silverback-website/.prettierrc#L1

### Jest
https://github.com/AmazeeLabs/silverback-mono/blob/d1e016eb43a1549d9d385595b8cbd0321c295cbf/apps/silverback-website/jest.config.js#L1-L3

### Lint-staged
https://github.com/AmazeeLabs/silverback-mono/blob/d1e016eb43a1549d9d385595b8cbd0321c295cbf/apps/silverback-website/.lintstagedrc#L1-L8

### Husky
https://github.com/AmazeeLabs/silverback-mono/blob/d1e016eb43a1549d9d385595b8cbd0321c295cbf/apps/silverback-website/.huskyrc#L1-L5

### NPM scripts
https://github.com/AmazeeLabs/silverback-mono/blob/484e36c6ff9c58395d777b900c8b25bffb99c3ea/apps/silverback-website/package.json#L61-L63

# BONUS!
If the use `preset`-package is updated and contains new contents for these configs, they should be updated in the project too.

**Comment by Leksat** [comment]
@pmelab take a look at https://github.com/AmazeeLabs/silverback-mono/pull/335
