### ISSUE TITLE
Optimise automated updates

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#369]
Packages are automatically updated by dependabot, which works in general, but has a couple of problems:

1. All packages have to be configured manually in the [config file](https://github.com/AmazeeLabs/silverback-mono/blob/development/.github/dependabot.yml). No way to auto-detect them.
2. Limited scheduling. Update pull requests are often created during worktime and collide with other pull requests. "Update on Sunday night" would be great.
3. Each dependency is updated in an individual pull request, which might not scale.

[Renovatebot](https://www.whitesourcesoftware.com/free-developer-tools/renovate) has better answers to at least some of these. Investigate if this is a feasible option and configure it if possible. Then also remove dependabot, or we start a war of machines.

**Comment by Leksat** [comment]
Not sure if it worked. I don't see any updates from Renovate in the repo.

The [Renovate log](https://app.renovatebot.com/dashboard#github/AmazeeLabs/silverback-mono) has only one job ran on Sunday, November 15th 2020, 9:55:05 am

And in that job log entry we have this:
```
DEBUG: Checking schedule(before 5am on monday, null)(branch="renovate/all")
DEBUG: Checking 1 schedule(s)(branch="renovate/all")
DEBUG: Checking schedule "before 5am on monday"(branch="renovate/all")
{
  "parsedSchedule": {
    "schedules": [
      {
        "t_b": [
          18000
        ],
        "d": [
          2
        ]
      }
    ],
    "exceptions": [],
    "error": -1
  }
}
DEBUG: Does not match schedule because 7 is not in 1(branch="renovate/all")
DEBUG: Package not scheduled(branch="renovate/all")
DEBUG: Skipping branch creation as not within schedule(branch="renovate/all")
```

@pmelab do you think we just need to wait another week? Or maybe ask Renovate team for support?

(As far as I know, Renovate bot should be executed every hour, plus on Github webhooks. Reference: https://github.com/renovatebot/renovate/issues/2080#issuecomment-402518435)

**Comment by Leksat** [comment]
@pmelab okay, looks like it worked this time: https://github.com/AmazeeLabs/silverback-mono/pull/486
