### ISSUE TITLE
Component folder structure/file naming

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#450]
More a question / request for documentation:

Why do we create folders for components with `index.tsx`/`index.stories.tsx` etc instead of skipping the folder and naming the file according to the component directly? Multiple open tabs called `index.tsx` always confuse me.

**Comment by pmelab** [comment]
@marcotisi We already talked about recent experience. What is your suggestion?

**Comment by marcotisi** [comment]
We adopted the Atomic Design pattern, so my suggestion is to use a flat folder structure, with a single `PascalCase` file per component.
Stories, mocks and tests are placed respectively inside a `__stories__`, `__mocks__` and `__tests__` folders nested at the same level.
Hooks and utilities have a dedicated folder and use the `camelCase` notation.
Every folder, except for `__stories__`, `__mocks__` and `__tests__` contain an `index.ts` file used to export everything from that folder.
Everything else uses lowercase slugged notation.
So, the example above would be written like this:

```
src
├── components
│   ├── 0-atoms
│   │   ├── __mocks__
│   │   │   ├── HeroTitle.mock.tsx
│   │   ├── __stories__
│   │   │   ├── HeroTitle.stories.tsx
│   │   ├── __tests__
│   │   │   ├── HeroTitle.test.tsx
│   │   ├── HeroTitle.tsx
│   │   ├── index.ts
│   ├── 1-molecules
│   │   ├── ...
│   ├── hooks
│   │   ├── useHeroTitle.tsx
│   │   ├── index.ts
│   ├── utils
│   │   ├── __tests__
│   │   │   ├── buildUrl.test.ts
│   │   ├── buildUrl.ts
│   │   ├── index.ts
│   ├── templates
│   │   ├── blog-page.tsx
│   ├── pages
│   │   ├── about-us.tsx
```

What do you think @pmelab @dan2k3k4  ?

**Comment by pmelab** [comment]
That sounds reasonable to me. The only thing I'm not a fan of are number-indexed folders (`0-atoms` ...), since these will show up in imports and cause mayhem should we ever have to adjust the order. Alphabetical ordering will put `layouts` at the wrong place, but in storybook they can be sorted correctly, and in source code its not a critical issue i think.
I would rather move everything thats not in storybook (`hooks`, `utils`) out of `components`. But maybe thats just a mistake in your "ascii art".

**Comment by marcotisi** [comment]
Removing number-indexed folders sounds fine for me 👍 

And yeah, you're right, that's a mistake in my "drawing" 😅 . Here's the updated version:

```
src
├── components
│   ├── atoms
│   │   ├── __mocks__
│   │   │   ├── HeroTitle.mock.tsx
│   │   ├── __stories__
│   │   │   ├── HeroTitle.stories.tsx
│   │   ├── __tests__
│   │   │   ├── HeroTitle.test.tsx
│   │   ├── HeroTitle.tsx
│   │   ├── index.ts
│   ├── molecules
│   │   ├── ...
├── hooks
│   ├── useHeroTitle.tsx
│   ├── index.ts
├── utils
│   ├── __tests__
│   │   ├── buildUrl.test.ts
│   ├── buildUrl.ts
│   ├── index.ts
├── templates
│   ├── blog-page.tsx
├── pages
│   ├── about-us.tsx
```

**Comment by pmelab** [comment]
We settled with the last suggestion by @marcotisi .
