### ISSUE TITLE
Standard solution for non-GraphQL client side requests

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#453]
Maybe we should settle on a standard solution (and provide some examples) for non-GraphQL client-side data fetches? [react-query](https://github.com/tannerlinsley/react-query) seems to be pretty popular these days.

**Comment by pmelab** [comment]
Interestingly `react-query` could also handle GraphQL requests: https://egghead.io/lessons/react-use-graphql-with-react-query-s-usequery

This would shave the apollo client off our js payload. Since we only use it for simple requests and not as the client-side data store it actually is.

**Comment by stewest** [comment]
What about https://github.com/matthew-andrews/isomorphic-fetch 
https://gist.github.com/stewest/9668b9d8f695ccf433b3e722c4eb0c7e

**Comment by pmelab** [comment]
We decided to go with `react-query`. It's on the "recommended packages" docs page.
