### ISSUE TITLE
Add favicon with Meta component

### ISSUE THREAD

**Issue by JohnAlbin** [amazeeio-solutions/silverback-mono#460]
We should use the Amazee Labs favicon.

In Gatsby, we'll need to use our Meta component.

For Storybook, it will use files that Gatsby adds to the `/public` directory during Gatsby build as long as you configure Storybook properly. See https://storybook.js.org/docs/configurations/add-custom-head-tags/

**Comment by stewest** [comment]
Ok, so the current apps/silverback-gatsby is empty of all components (in that storybook).

**Comment by stewest** [comment]
Hi @JohnAlbin just wanted to ask if there already is a "Meta component" we've done somewhere else?

**Comment by stewest** [comment]
Oh, I think it is this one https://github.com/AmazeeLabs/gatsby-starter-amazee/blob/development/src/components/common/Meta/index.tsx

**Comment by stewest** [comment]
I believe this can only be done after https://github.com/AmazeeLabs/silverback-mono/issues/125 is completed

**Comment by pmelab** [comment]
Part of https://github.com/AmazeeLabs/silverback-mono/milestone/3
