### ISSUE TITLE
Refactor Navigation component to be more accessible

### ISSUE THREAD

**Issue by JohnAlbin** [amazeeio-solutions/silverback-mono#466]
At mobile sizes, the current `Navigation` component uses a select element to navigate to different URLs. This makes it hard for users to see the navigation structure at a glance. It also doesn't work for a multi-level navigation tree.

Let's refactor it to have a button to open a modal with the navigation links.

Related: AmazeeLabs/gatsby-starter-amazee#92, AmazeeLabs/gatsby-starter-amazee#93, AmazeeLabs/gatsby-starter-amazee#94

**Comment by pmelab** [comment]
Covered by #703
