### ISSUE TITLE
Add a setup to handle Forms and Form Validation

### ISSUE THREAD

**Issue by dan2k3k4** [amazeeio-solutions/silverback-mono#467]
We need a good standard setup for handling forms and form validation.

For our projects, we explored `Formik` and `Yup` and they are proving to be highly useful for this purpose. So let's standardise on that.

- [ ] Add [Formik](https://www.npmjs.com/package/formik)
- [ ] Add [Yup](https://www.npmjs.com/package/yup)
- [ ] Add [@types/yup](https://www.npmjs.com/package/@types/yup)
- [ ] Add example using `<Formik />` and `Yup`
- [ ] Add documentation

More info can be read in this [blog on bitsrc.io](https://blog.bitsrc.io/handling-react-forms-and-validation-with-formik-and-yup-dc789fd9e485).

**Comment by pmelab** [comment]
Resolved in #568
