### ISSUE TITLE
Drupal "Admin UI" package

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#479]
Add some administration convenience features to the drupal setup recipe

- [ ] Coffee
- [ ] Admin toolbar
- [ ] Field UI
- [ ] ...

**Comment by dan2k3k4** [comment]
I also add a vote for using [drupal/gin](https://www.drupal.org/project/gin) for the Admin UI.

It has slightly more features than `Claro`, and that's where the new features get tested first before moving to Claro / Core.

**Comment by pmelab** [comment]
Gin was discussed this with UX, and it was deemed a little too "off Drupal" and doesn't justify the effort of maintaining an unstable dependency right now.

**Comment by stewest** [comment]
I think this is something @luqmaanessop  and I could try? But would need some more specifics on what type of tests we want to do on these Drupal Admin modules.

**Comment by pmelab** [comment]
Part of https://github.com/AmazeeLabs/silverback-mono/milestone/3
