### ISSUE TITLE
`silverback init` tries to symlink some storybook

### ISSUE THREAD

**Issue by Leksat** [amazeeio-solutions/silverback-mono#483]
Got this with a fresh drupal installation on `silverback init`:
```
PHP Warning:  symlink(): No such file or directory in /vendor/amazeelabs/silverback-cli/src/AmazeeLabs/Silverback/Commands/Init.php on line 148
```

**Comment by Leksat** [comment]
@pmelab should this code be removed?
https://github.com/AmazeeLabs/silverback-mono/blob/4ca75584c6ff013f82cf0d280d837a9545039d09/packages/composer/amazeelabs/silverback-cli/src/AmazeeLabs/Silverback/Commands/Init.php#L146-L149

I don't get what it tries to do.

**Comment by dan2k3k4** [comment]
The root `storybook/dist` folder only exists after a storybook build, so we should add a `.gitkeep` into the root: `storybook/dist/.gitkeep` so the symlink can be created before the frontend/storybook build has been executed.

**Comment by dan2k3k4** [comment]
But it looks like there is no longer a root `storybook` in the `silverback-drupal` setup.

Whereas the older setup had this:
https://github.com/AmazeeLabs/silverback/blob/master/assets/storybook/dist/.gitignore

**Comment by pmelab** [comment]
Yes, this is a leftover. We don't scaffold storybook by default in Drupal any more.
