### ISSUE TITLE
Issues with pinned packages

### ISSUE THREAD

**Issue by Leksat** [amazeeio-solutions/silverback-mono#489]
We have some pinned packages in our `package.json` files (e.g. `"some-package": "1.2.3"`). When Renovate Bot updates them, it keeps them pinned. But then it can turn into a mess. Example:
- I create a new Gatsby app from our gatsby-starter.
- `@graphql-codegen/typescript-operations` was pinned there to some version.
- Later Renovate Bot updated `@graphql-codegen/typescript-operations` (and other `@graphql-codegen` packages) to the next version in the starter, but not in my app, because it was still in a PR.
- After I pulled changes from development, codegen stopped to work.
- The reason was:
  - `@graphql-codegen/typescript-operations` was pinned to an older version in my app.
  - But other `@graphql-codegen` packages were updated from the monorepo.
  - So codegen packages were incompatible and I've got `& Pick<DrupalNodeArticle, '[object Object]' | '[object Object]'>` in the generated code.

**Comment by Leksat** [comment]
@pmelab I guess the easiest would be to go through all `package.json` files and prefix pinned versions with `^`. But maybe you have better ideas?

**Comment by Leksat** [comment]
BTW, at first I thought that `@graphql-codegen` packages could avoid this issue by defining dependencies properly. But it looks like some packages there are not direct dependencies of each other, but siblings:
<img width="1008" alt="Screenshot 2020-11-25 at 10 24 31" src="https://user-images.githubusercontent.com/989015/100195615-acc88b80-2f08-11eb-8a45-3b973a575f4d.png">

**Comment by pmelab** [comment]
In general, we should use `^` version ranges and not fully fixed versions.
And ideally, pull requests don't live over a weekend so renovatebot doesn't collide. This won't be always possible, but its additional "motivation" 😄

**Comment by Leksat** [comment]
@pmelab so do you agree with my plan for adding `^` everywhere?
