### ISSUE TITLE
Monorepo initialisation command

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#495]
We could simplify the setup for local development by introducing a dedicated `yarn setup` script. This would allow us to:

* Check for runtime requirements (see #482 )
* Run basic tests of the monorepo is locally operational
* Trigger additional build steps (see #490 )

**Comment by Leksat** [comment]
3 (and maybe 2) are fixed in #494

**Comment by Leksat** [comment]
In my opinion #528 solves 1. Please reopen otherwise.
