### ISSUE TITLE
Make ESLint `simple-import-sort` rule aware of TypeScript paths aliases

### ISSUE THREAD

**Issue by marcotisi** [amazeeio-solutions/silverback-mono#507]
Configure ESLint `simple-import-sort` plugin in a way that it recognizes TypeScript path aliases and treats them as local packages.

**Actual behavior**
```ts
import { ParagraphCopyText } from '@atoms';
import { ParagraphAccordion } from '@organisms';
import { Company } from '@typings';
import React from 'react';
import { useTranslation } from 'react-i18next';
```

**Correct behavior**
```ts
import React from 'react';
import { useTranslation } from 'react-i18next';

import { ParagraphCopyText } from '@atoms';
import { ParagraphAccordion } from '@organisms';
import { Company } from '@typings';
```

**Comment by pmelab** [comment]
After some discussions with @Leksat , he convinced me that we should avoid typescript path aliases. Importing is managed by the IDE anyway, and aliases add complexity to the build process (storybook, jest, gatsby ...). It's more a "asthetic" issue, but I might get over looking at `../../../`.

@marcotisi Whats your take on this?

**Comment by marcotisi** [comment]
Yeah, it has some overhead when setting up TypeScript with path aliases, but aren't that setup already managed by `@amazeelabs/gatsby-theme-core`? 
If we can automate that I'm more by the side of using path aliases, otherwise I'm also fine with having relative imports.

**Comment by pmelab** [comment]
It is managed by `gatsby-theme-core` right now, but this setup has to be maintained, and has broken multiple times in the last year (when storybook included typescript, when gatsby included typescript ...). Build tools change all the time, and I wonder if its worth to keep this feature as long as it is not out-of-the-box in typescript. Not even `tsc` resolves path aliases when emitting javascript. You need to use a patched version.

**Comment by marcotisi** [comment]
So let's remove that, it's only a pleasure for the eyes, we can do fine also without it.

**Comment by pmelab** [comment]
We decided some time ago not to use aliases.
