### ISSUE TITLE
Documentation for loadable components

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#561]
- [x] why use them
- [x] when to use them
- [x] how to use them

**Comment by dan2k3k4** [comment]
The [React docs](https://reactjs.org/docs/code-splitting.html#reactlazy) have a note added on code splitting linking to [Loadable Components](https://loadable-components.com/)

**Comment by pmelab** [comment]
Yes, @marcotisi already implemented it successfully in a client project. We just want to make sure the knowledge persists.
