### ISSUE TITLE
Auto-refresh Drupal install cache on release

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#611]
This is something we want to reuse I think. Maybe we could event turn it into a Github action in the future.

_Originally posted by @pmelab in https://github.com/AmazeeLabs/silverback-mono/pull/610#discussion_r590068911_

**Comment by Leksat** [comment]
What's done so far:

In the Release job, before `lerna publish`, we update the install cache https://github.com/AmazeeLabs/silverback-mono/blob/758273ce584bd11eabbadf113d809d99d010d4ea/.github/workflows/release.yml#L76-L108
Which means we always have the most fresh Drupal install cache in the `main` branch. (Actually _not always_, an edge case can happen if a branch is created from `main` before the Release job is done)

Next, on renovate PRs we have a check for new config changes coming from Drupal updates https://github.com/AmazeeLabs/silverback-mono/blob/758273ce584bd11eabbadf113d809d99d010d4ea/.github/workflows/renovate-checks.yml#L64-L80

I did a couple of tests (#614, #615). It looks working.

So we can live without https://github.com/renovatebot/renovate/issues/8804

**Comment by Leksat** [comment]
I added the last bit in https://github.com/AmazeeLabs/silverback-mono/pull/659

Overview of the complete solution:
- In the Release workflow we update Drupal cache if needed
- In the Test workflow we run `silverback setup --no-config-import` and check if there are any Git changes. If there are, we throw an error and print the instructions.
