### ISSUE TITLE
gatsby-source-silverback: GraphQL errors are not reported

### ISSUE THREAD

**Issue by Leksat** [amazeeio-solutions/silverback-mono#670]
Example:
https://github.com/AmazeeLabs/silverback-mono/blob/b7ec33d0ddb60059acda94b161580d218c205bc3/packages/npm/%40amazeelabs/gatsby-source-silverback/src/helpers/drupal-nodes.ts#L27

In case if a GraphQL responses with an error, the error is ignored and the code fails in some other place (e.g. `TypeError: Cannot read property 'filter' of undefined`)

There may be more cases like this in the plugin code.

**Comment by pmelab** [comment]
maybe our query executor should check for errors

**Comment by pmelab** [comment]
was fixed in https://github.com/AmazeeLabs/silverback-mono/commit/360ca90d911cf310bb7fc3c557b3ec0610fc06e1
