### ISSUE TITLE
GraphQL data producer for Gutenberg Content

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#706]
Currently we have some custom code in projects in place that parses and sanitizes Gutenberg documents to be consumed via GraphQL. This should be extracted to a reusable GraphQL data producer.

- parse gutenberg documents
- handle referenced entities
- ...

**Comment by Leksat** [comment]
One thing I noticed recently. In the project we have string fields in the GraphQL schema. Some of them return plain text, others produce HTML. Frontend has no hint to guess this from the schema.

For this issue (and for the future projects) I would add `Html` suffix to field names. For example

```graphql
type Page {
  title: String!
  descriptionHtml: String!
}
```

**Comment by pmelab** [comment]
We could also add a `Html` scalar.

```graphql
scalar Html

type Page {
  title: String!
  description: Html!
}
```

Under the hood it's still a string, but we could feed that into typechecking.

**Comment by Leksat** [comment]
Yeah, but when you work with fetched data in a React component, the type is not really visible.

**Comment by pmelab** [comment]
It is! One can pass a `ScalarsMap` into codegen. So when it encounters `Html` it can emit a dedicated typescript type for it.

**Comment by pmelab** [comment]
We could even declare that it's not compatible to string, so nobody prints it by accident 🤯

**Comment by pmelab** [comment]
Solved by now. See `silverback_gatsby` module.
