### ISSUE TITLE
Add eslint-plugin-tailwindcss

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#713]
https://www.npmjs.com/package/eslint-plugin-tailwindcss

**Comment by stewest** [comment]
https://github.com/AmazeeLabs/silverback-mono/pull/new/feature/713-Add-Eslint-plugin-tailwindcss

**Comment by stewest** [comment]
Ok, got an error I need to update here 
Error: recipes/add-storybook.ts(73,1): error TS1109: Expression expected.
Error: recipes/add-storybook.ts(73,3): error TS1005: ';' expected.

**Comment by stewest** [comment]
and error from something I didn't update

warning package.json: "dependencies" has dependency "@amazeelabs/eslint-config" with range "^1.3.1" that collides with a dependency in "devDependencies" of the same name with version "^1.3.0"
warning package.json: "dependencies" has dependency "@amazeelabs/jest-preset" with range "^1.3.3" that collides with a dependency in "devDependencies" of the same name with version "^1.3.1"

**Comment by stewest** [comment]
This should resolve the above https://github.com/AmazeeLabs/silverback-mono/pull/752

**Comment by stewest** [comment]
Yay, tests pass

**Comment by stewest** [comment]
https://github.com/AmazeeLabs/silverback-mono/pull/751
