### ISSUE TITLE
drupal/cypress latest version not published on packages.drupal.org?

### ISSUE THREAD

**Issue by carstendietrich** [amazeeio-solutions/silverback-mono#728]
Hello,

I am currently checking out the drupal/cypress module, it seems that the latest versions aren't available via composer using the package.drupal.org repository.

When using `composer require --dev drupal/cypress` version `2.3.1` is added to my project. Any clues why the latest versions aren't available via packages.drupal.org?

working:
https://ftp.drupal.org/files/projects/cypress-2.3.1.zip

missing:
https://ftp.drupal.org/files/projects/cypress-2.3.2.zip

ty

**Comment by Leksat** [comment]
Published 2.3.14, thanks for reporting!
