### ISSUE TITLE
GraphQL: entity reference translations

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#742]
We have to get this merged so we don't have to rely on a patch: https://github.com/drupal-graphql/graphql/pull/974/files

**Comment by Leksat** [comment]
Submitted a new PR: https://github.com/drupal-graphql/graphql/pull/1232

**Comment by Leksat** [comment]
Now waiting for 8.x-4.2 release.

**Comment by pmelab** [comment]
The wait is over.
