### ISSUE TITLE
Extract Cypress to a separate package

### ISSUE THREAD

**Issue by unamaria** [amazeeio-solutions/silverback-mono#93]
- Move anything Cypress-related out of the Gatsby starter
- Create or find a node package that we can add 
- Update starter to include the package and create an empty directory where Cypress-related stuff will live
- Test: is it easier to make changes (e.g. update)?

**Comment by pmelab** [comment]
We don't really do testing for Gatsby itself at all. Backend services (e.g. Drupal) are tested with Cypress, the UI components are tested with Storybook/Chromatic and for the "Gatsby" part in between we rely on GraphQL Codegen and Typescript.
