### ISSUE TITLE
`eslint-plugin-tailwindcss` does not seem to work

### ISSUE THREAD

**Issue by Leksat** [amazeeio-solutions/silverback-mono#931]
A Renovate update (https://github.com/AmazeeLabs/silverback-mono/pull/930) brought `eslint-plugin-tailwindcss` v3 which we use in [`@amazeelabs/eslint-config`](https://github.com/AmazeeLabs/silverback-mono/tree/development/packages/npm/%40amazeelabs/eslint-config).

I decided to check if it works and started from its readme to see which rules it provides. And it looks like it does nothing by default, because we do not use the recommended configuration: https://github.com/francoismassart/eslint-plugin-tailwindcss#configuration

**Comment by Leksat** [comment]
@pmelab do you know if it ever worked?

**Comment by pmelab** [comment]
Works by now
