### ISSUE TITLE
Extract Storybook to a separate package

### ISSUE THREAD

**Issue by unamaria** [amazeeio-solutions/silverback-mono#94]
- Move anything Storybook-related out of the Gatsby starter
- Create or find a node package that we can add 
- Update starter to include the package and create an empty directory where Storybook-related stuff will live
- Test: is it easier to make changes (e.g. update)?

**Comment by pmelab** [comment]
We tested this approach during the last project, and it turned out that there are too many interdependencies between Gatsby and the components. Separating the two is more trouble than its worth. And just doing it for the prospect of "using the same components somewhere else" is premature.
