### ISSUE TITLE
Create UI Gatsby theme

### ISSUE THREAD

**Issue by unamaria** [amazeeio-solutions/silverback-mono#95]
Should include UI components, like a page wrapper (with needed providers like helmet’s) and common ones like icon or form elements. Takes care of its own configuration and stuff like declaring modules for assets (if needed). Added by default in Gatsby starter.

- Add any React components that are reusable across projects from the existing starter
- Add any configuration needed for it to work properly with the starter
- Include from starter
- Come up with a sane name/way to clearly reference it

**Comment by pmelab** [comment]
We where looking at themes, but most of it is doable with simple react component composition. And since themes are a static inheritance mechanism, they are less flexible.
